[package]
name = "Arithmetic-Coding"
version = "0.1.0"
authors = ["kmgx <kmgx@declaverie.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.3"
rug = "1.6.0"